/** Planilha/foto atual (out/2026) — números de lote e situação financeira. */
export type TableRow = {
  clientName: string
  lotNumbers: string[] | null
  entrada: number | null
  /** "pg" = quitado na planilha, sem valor de entrada separado */
  entradaPg?: boolean
  parcelasPagas: number | null
  totalPagoParcelas: number | null
  totalVenda: number | null
  /** Cliente marcado em azul na planilha */
  emDia?: boolean
}

export const TABLE_ROWS: TableRow[] = [
  {
    clientName: 'Raimundo',
    lotNumbers: null,
    entrada: 25000,
    parcelasPagas: 43,
    totalPagoParcelas: 67000,
    totalVenda: 90000,
    emDia: true,
  },
  {
    clientName: 'Alex',
    lotNumbers: ['01', '02'],
    entrada: 10000,
    parcelasPagas: 27,
    totalPagoParcelas: null,
    totalVenda: 40000,
    emDia: true,
  },
  {
    clientName: 'Deurismar',
    lotNumbers: ['03'],
    entrada: 4000,
    parcelasPagas: 2,
    totalPagoParcelas: 4600,
    totalVenda: 25000,
    emDia: true,
  },
  {
    clientName: 'Lilian',
    lotNumbers: ['04'],
    entrada: 4000,
    parcelasPagas: 47,
    totalPagoParcelas: 15750,
    totalVenda: 20000,
  },
  {
    clientName: 'Eudes',
    lotNumbers: ['05'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Leonardo',
    lotNumbers: ['06'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Evandir',
    lotNumbers: ['07'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Caique',
    lotNumbers: ['08'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Daniel',
    lotNumbers: ['09', '10'],
    entrada: 4000,
    parcelasPagas: 15,
    totalPagoParcelas: 11500,
    totalVenda: 40000,
  },
  {
    clientName: 'Régia',
    lotNumbers: ['11'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Fernando',
    lotNumbers: ['12'],
    entrada: 2000,
    parcelasPagas: 24,
    totalPagoParcelas: 8000,
    totalVenda: 20000,
  },
  {
    clientName: 'Pago',
    lotNumbers: ['13'],
    entrada: null,
    entradaPg: true,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Pago',
    lotNumbers: ['14'],
    entrada: null,
    entradaPg: true,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Tânia',
    lotNumbers: ['15'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Jajá',
    lotNumbers: ['16'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Naldo',
    lotNumbers: ['17'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Robertânia',
    lotNumbers: ['18'],
    entrada: 2500,
    parcelasPagas: 1,
    totalPagoParcelas: null,
    totalVenda: 25000,
    emDia: true,
  },
  {
    clientName: 'Davi',
    lotNumbers: ['19'],
    entrada: 2000,
    parcelasPagas: 1,
    totalPagoParcelas: 250,
    totalVenda: 25000,
    emDia: true,
  },
  {
    clientName: 'Barroso',
    lotNumbers: ['21'],
    entrada: null,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
    emDia: true,
  },
  {
    clientName: 'Jonas',
    lotNumbers: ['22', '23', '26', '27'],
    entrada: 7500,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 100000,
  },
  {
    clientName: 'Maria Lúcia',
    lotNumbers: ['30'],
    entrada: 2000,
    parcelasPagas: 10,
    totalPagoParcelas: 4500,
    totalVenda: 20000,
    emDia: true,
  },
  {
    clientName: 'Denir',
    lotNumbers: ['31'],
    entrada: 0,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
  },
  {
    clientName: 'Marquinhos',
    lotNumbers: ['32', '40'],
    entrada: 3000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 40000,
  },
  {
    clientName: 'Marcelo',
    lotNumbers: ['33'],
    entrada: 2000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 20000,
    emDia: true,
  },
  {
    clientName: 'Rerin',
    lotNumbers: ['42'],
    entrada: 2000,
    parcelasPagas: 9,
    totalPagoParcelas: 4250,
    totalVenda: 20000,
  },
  {
    clientName: 'Iranildo',
    lotNumbers: ['43', '44'],
    entrada: 4000,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 40000,
  },
  {
    clientName: 'Fernanda',
    lotNumbers: ['45'],
    entrada: 500,
    parcelasPagas: null,
    totalPagoParcelas: null,
    totalVenda: 30000,
  },
  {
    clientName: 'Sarah',
    lotNumbers: ['46'],
    entrada: 3000,
    parcelasPagas: 1,
    totalPagoParcelas: null,
    totalVenda: 30000,
    emDia: true,
  },
]

export const CLIENT_RENAMES: { from: string; to: string }[] = [
  { from: 'Lilian Cristina', to: 'Lilian' },
  { from: 'Maria lucia', to: 'Maria Lúcia' },
  { from: 'Marquinho oficina', to: 'Marquinhos' },
  { from: 'Fernando Guerreiro', to: 'Fernando' },
]

export const LOT_RENUMBER: { clientMatch: string; fromLote: string; toLote: string }[] = [
  { clientMatch: 'Alex', fromLote: '65', toLote: '01,02' },
  { clientMatch: 'Lilian', fromLote: '7', toLote: '04' },
  { clientMatch: 'Barroso', fromLote: '06', toLote: '21' },
  { clientMatch: 'Evandir', fromLote: 'Evandir', toLote: '07' },
  { clientMatch: 'Caique', fromLote: '87', toLote: '08' },
  { clientMatch: 'Daniel', fromLote: '54', toLote: '09,10' },
  { clientMatch: 'Fernando', fromLote: '8', toLote: '12' },
  { clientMatch: 'Tânia', fromLote: '88', toLote: '15' },
  { clientMatch: 'Maria Lúcia', fromLote: '65', toLote: '30' },
  { clientMatch: 'Denir', fromLote: '33', toLote: '31' },
  { clientMatch: 'Marquinhos', fromLote: '71', toLote: '32' },
  { clientMatch: 'Marquinhos', fromLote: '76', toLote: '40' },
  { clientMatch: 'Marcelo', fromLote: '77', toLote: '33' },
  { clientMatch: 'Rerin', fromLote: '44', toLote: '42' },
  { clientMatch: 'Iranildo', fromLote: '88', toLote: '43,44' },
  { clientMatch: 'Leonardo', fromLote: '22', toLote: '06' },
]
